User.create(userName: 'admin',
            email: 'admin@admin.com',
            password_digest: BCrypt::Password.create('admin'),
            role: 'ADMIN')

Car.create( model: 'Kia Rio',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '15',
        doors: '4',
        luggages: '3',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '1.jpeg'), 'image/*', true))

Car.create( model: 'Mitsubishi Montero sport',
        color: 'Gray',
        bodyStyle: 'SUVs',
        pricePerDay: '40',
        doors: '4',
        luggages: '1',
        seats: '2',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '400',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '2.jpeg'), 'image/*', true))

Car.create( model: 'Hyundai Creta',
        color: 'Gray',
        bodyStyle: 'Sedan',
        pricePerDay: '27',
        doors: '4',
        luggages: '4',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '270',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '3.jpeg'), 'image/*', true))
Car.create( model: 'Nissan Sunny',
        color: 'Gray',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '4.jpeg'), 'image/*', true))
Car.create( model: 'Nissan Micra',
        color: 'Gray',
        bodyStyle: 'Hatchbacks',
        pricePerDay: '13',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '250',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '5.jpeg'), 'image/*', true))
Car.create( model: 'Hyundai Elantra',
        color: 'Black',
        bodyStyle: 'Sedan',
        pricePerDay: '25',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '350',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '6.jpeg'), 'image/*', true))
Car.create( model: 'Hyundai Accent',
        color: 'Red',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '7.jpeg'), 'image/*', true))
Car.create( model: 'Kia Sportage',
        color: 'Brown',
        bodyStyle: 'SUVs',
        pricePerDay: '30',
        doors: '4',
        luggages: '4',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '400',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '8.jpeg'), 'image/*', true))
Car.create( model: 'Toyota Yaris',
        color: 'Black',
        bodyStyle: 'Coupe',
        pricePerDay: '15',
        doors: '2',
        luggages: '1',
        seats: '2',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: '5-speed shiftable',
        rentDeposit: '200',
        carImg: Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', '9.jpeg'), 'image/*', true))